import type { SkillCategory } from '@/shared/skill';

export const skillRegistry = {
  html: {
    id: 'html',
    name: 'HTML',
    category: 'frontend',
    priority: 100,
  },
  css: {
    id: 'css',
    name: 'CSS',
    category: 'frontend',
    priority: 200,
  },
  scss: {
    id: 'scss',
    name: 'SCSS',
    category: 'frontend',
    priority: 300,
  },
  javascript: {
    id: 'javascript',
    name: 'JavaScript',
    category: 'frontend',
    priority: 400,
  },
  typescript: {
    id: 'typescript',
    name: 'TypeScript',
    category: 'frontend',
    priority: 500,
  },
  vue2: {
    id: 'vue2',
    name: 'Vue 2',
    category: 'frontend',
    priority: 600,
  },
  vue3: {
    id: 'vue3',
    name: 'Vue 3',
    category: 'frontend',
    priority: 700,
  },
  compositionApi: {
    id: 'compositionApi',
    name: 'Composition API',
    category: 'frontend',
    priority: 800,
  },
  react: {
    id: 'react',
    name: 'React',
    category: 'frontend',
    priority: 900,
  },
  nuxt: {
    id: 'nuxt',
    name: 'Nuxt',
    category: 'frontend',
    priority: 1000,
  },
  nextjs: {
    id: 'nextjs',
    name: 'Next.js',
    category: 'frontend',
    priority: 1100,
  },
  vueRouter: {
    id: 'vueRouter',
    name: 'Vue Router',
    category: 'frontend',
    priority: 1200,
  },
  reactRouter: {
    id: 'reactRouter',
    name: 'React Router',
    category: 'frontend',
    priority: 1300,
  },
  pinia: {
    id: 'pinia',
    name: 'Pinia',
    category: 'frontend',
    priority: 1400,
  },
  vuex: {
    id: 'vuex',
    name: 'Vuex',
    category: 'frontend',
    priority: 1500,
  },
  primevue: {
    id: 'primevue',
    name: 'PrimeVue',
    category: 'frontend',
    priority: 1600,
  },
  vuetify: {
    id: 'vuetify',
    name: 'Vuetify',
    category: 'frontend',
    priority: 1700,
  },
  tailwind: {
    id: 'tailwind',
    name: 'Tailwind CSS',
    category: 'frontend',
    priority: 1800,
  },
  storybook: {
    id: 'storybook',
    name: 'Storybook',
    category: 'frontend',
    priority: 1900,
  },
  d3: {
    id: 'd3',
    name: 'D3.js',
    category: 'frontend',
    priority: 2000,
  },
  axios: {
    id: 'axios',
    name: 'Axios',
    category: 'frontend',
    priority: 2100,
  },
  inertia: {
    id: 'inertia',
    name: 'Inertia.js',
    category: 'frontend',
    priority: 2200,
  },
  nodejs: {
    id: 'nodejs',
    name: 'Node.js',
    category: 'backend',
    priority: 100,
  },
  nestjs: {
    id: 'nestjs',
    name: 'NestJS',
    category: 'backend',
    priority: 200,
  },
  express: {
    id: 'express',
    name: 'Express',
    category: 'backend',
    priority: 300,
  },
  restApi: {
    id: 'restApi',
    name: 'REST API',
    category: 'backend',
    priority: 500,
  },
  graphql: {
    id: 'graphql',
    name: 'GraphQL',
    category: 'backend',
    priority: 600,
  },
  websocket: {
    id: 'websocket',
    name: 'WebSocket',
    category: 'backend',
    priority: 700,
  },
  postgresql: {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    priority: 100,
  },
  mongodb: {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    priority: 200,
  },
  redis: {
    id: 'redis',
    name: 'Redis',
    category: 'database',
    priority: 300,
  },
  jest: {
    id: 'jest',
    name: 'Jest',
    category: 'testing',
    priority: 100,
  },
  vitest: {
    id: 'vitest',
    name: 'Vitest',
    category: 'testing',
    priority: 200,
  },
  playwright: {
    id: 'playwright',
    name: 'Playwright',
    category: 'testing',
    priority: 300,
  },
  cypress: {
    id: 'cypress',
    name: 'Cypress',
    category: 'testing',
    priority: 400,
  },
  fsd: {
    id: 'fsd',
    name: 'Feature-Sliced Design',
    category: 'architecture',
    priority: 100,
  },
  git: {
    id: 'git',
    name: 'Git',
    category: 'tooling',
    priority: 100,
  },
  vite: {
    id: 'vite',
    name: 'Vite',
    category: 'tooling',
    priority: 200,
  },
  webpack: {
    id: 'webpack',
    name: 'Webpack',
    category: 'tooling',
    priority: 300,
  },
  pnpm: {
    id: 'pnpm',
    name: 'pnpm',
    category: 'tooling',
    priority: 400,
  },
  turborepo: {
    id: 'turborepo',
    name: 'Turborepo',
    category: 'tooling',
    priority: 500,
  },
  eslint: {
    id: 'eslint',
    name: 'ESLint',
    category: 'tooling',
    priority: 600,
  },
  prettier: {
    id: 'prettier',
    name: 'Prettier',
    category: 'tooling',
    priority: 700,
  },
  husky: {
    id: 'husky',
    name: 'Husky',
    category: 'tooling',
    priority: 800,
  },
  lintstaged: {
    id: 'lintstaged',
    name: 'lint-staged',
    category: 'tooling',
    priority: 900,
  },
  zod: {
    id: 'zod',
    name: 'Zod',
    category: 'tooling',
    priority: 1000,
  },
  sentry: {
    id: 'sentry',
    name: 'Sentry',
    category: 'tooling',
    priority: 1100,
  },
  plop: {
    id: 'plop',
    name: 'Plop',
    category: 'tooling',
    priority: 1200,
  },
  docker: {
    id: 'docker',
    name: 'Docker',
    category: 'devops',
    priority: 100,
  },
  ciCd: {
    id: 'ciCd',
    name: 'CI/CD',
    category: 'devops',
    priority: 200,
  },
  openai: {
    id: 'openai',
    name: 'OpenAI API',
    category: 'ai',
    priority: 100,
  },
  aiAgents: {
    id: 'aiAgents',
    name: 'AI Agents',
    category: 'ai',
    priority: 200,
  },
} as const;

export const categoryTitles: Record<SkillCategory, string> = {
  frontend: 'Frontend',
  backend: 'Backend',
  database: 'Databases',
  testing: 'Testing',
  architecture: 'Architecture',
  tooling: 'Tooling',
  devops: 'DevOps',
  ai: 'AI',
};

export const categoryOrder = [
  'frontend',
  'backend',
  'database',
  'testing',
  'architecture',
  'tooling',
  'devops',
  'ai',
] as const;
